### ISSUE TITLE
代码下载下来不能运行

### ISSUE THREAD

**Issue by mingliao** [chenbin11200/RequireJsComponentExample#1]
您好，我正在慕课上观看您的视频教程http://www.imooc.com/learn/99，您的视频教程给了我很大的启发【虽然刚看了前面两集】，先谢谢了。然后百度到这个下载源码的地址，不过我git下来之后，发现这里面的代码不能用页面上4个按钮点击都没效果。请帮忙有空更正下，O(∩_∩)O  感激不尽。谢谢。

**Comment by chenbin11200** [comment]
你好。代码我在firefox和chrome下都测试通过，唯独IE下会有一个底部提示框，Internet Explorer restricted this webpage from running scrips or ActiveX controls. 点击Allow blocked content后即可。
这套教程不是我做的，不敢居功。我也只是一个参与学习者，代码是跟着阿当老师做的，然后做了调试和修正，都经过测试，最后把源码放出来提供学友们参考。我这里每一个commit都对应一个章节，唯一有问题的commit可能是11，12，13三个章节，问题我在14章源码里修正了。具体可以看http://www.imooc.com/video/1658我的留言。
如果还是不能用，欢迎再给我留言。

**Comment by mingliao** [comment]
哈哈，不好意思，后面自己调试了一下，是因为ruquirejs引用了jqueryui的url，网络原因，js没加载进来才有问题。谢谢。后面的章节还没看到。有问题再找你指教。O(∩_∩)O
